### ISSUE TITLE
not works on logseq 0.8.16

### ISSUE THREAD

**Issue by FelixHuoEZ** [YU000jp/logseq-plugin-panel-coloring#1]
There is no boarder on the block with specified tags.
![image](https://user-images.githubusercontent.com/13887263/212141826-c1d0fd37-eae8-40de-9f7d-c0987e1f6f03.png)

**Comment by mharmel** [comment]
Nothing works in 0.8.17 for me – I don't get colored custom tags or any colored tags at all.

The admonitions picker shows up both via block context menu and the /slash command, and also inserts the tags as expected, but they also have no effect.

Mac OS Ventura 13.1 (22C65)

**Comment by YU000jp** [comment]
You were right.

problem solved

Please install the newly released version.


https://github.com/logseq/marketplace/pull/345
(Blocked by security CORS policy. Now that this pull request has passed, it will be unblocked.)
