### ISSUE TITLE
Tag Coloring and Page Coloring not working

### ISSUE THREAD

**Issue by MentalBrain** [YU000jp/logseq-plugin-panel-coloring#15]
I just installed this plugin for the first time and can't get tag coloring to work at all. Page coloring shows the colored bar under the shortcut but there's no color on the page itself. I'm using Logseq 0.8.9.

**Comment by YU000jp** [comment]
I have conducted a review of the public version and did not find any abnormalities. I kindly request you to try it again with the default theme and with other plugins turned off, if possible.

**Comment by MentalBrain** [comment]
That's strange. I tried disabling all plugins and themes except for your plugin, and nothing changed. The admonitions do work in both states by the way. Just not custom tags and page coloring.

**Comment by YU000jp** [comment]
I'm not sure if it will resolve the issue, but we have performed refactoring and released a new update. Please update or reinstall the plugins along with the latest version of Logseq.

**Comment by MentalBrain** [comment]
Thanks, I did update. Now the custom hashtags have the colors I picked just around the hashtag text, but the block they are in stays the same (no color). Page coloring is still not working.

**Comment by YU000jp** [comment]
Could you please take a screenshot of that screen so that I can investigate it?

**Comment by MentalBrain** [comment]
Sure, here's screenshots of my settings and how they affect or don't affect my hashtags and pages:
<img width="524" alt="Logseq_C8XYj13qG9" src="https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/110931091/a93cc72a-009f-4fe6-92b4-ca6135d2cd31">
<img width="693" alt="Logseq_o8TgdENYdX" src="https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/110931091/641d0ff4-c778-4d5d-8c71-c9055cfd13de">
<img width="527" alt="Logseq_XUvu7vRz4b" src="https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/110931091/44b33509-b327-4d51-913e-3c1a16c1e543">
<img width="166" alt="Logseq_Q1JVsCWFwb" src="https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/110931091/7e891956-6832-4d27-ac68-bb3ec4b221a4">
<img width="708" alt="Logseq_4YedVyu6zq" src="https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/110931091/d072231c-29e1-4ac5-aa54-ac99503252be">

**Comment by MentalBrain** [comment]
Actually, I found that if I get rid of "Test Page" so that the name is just "Tangerine", it works! I'd just suggest changing the documentation to specify you need to put the entire page name in the field, not just a word. 

Also the colored line under the page in the left sidebar shows up if it's Favorited but not if it's Recent. I don't know if that's intentional but it would be great if it showed up in both places.

**Comment by YU000jp** [comment]
I have incorporated some of your opinions. I still don't know the reason why Tag Coloring isn't working.

**Comment by MentalBrain** [comment]
Thanks, unfortunately things are still the same with custom hashtags. They only change the color of the hashtag text and not the whole block like admonitions do.

I really appriciate your work on this plugin, but I've decided Logseq isn't going to work for me right now and I'm switching to a different app. Just too many things that don't work quite right and some features I want that Logseq probably won't have for a long time, if ever. But thanks again for your help!

**Comment by YU000jp** [comment]
I see.
I apologize for taking up your valuable time due to problems.

**Comment by MentalBrain** [comment]
No, it's fine. This is just part of experimenting with new software. Logseq is great in a lot of ways, but overall not quite what I need.
