### ISSUE TITLE
Option to append the tag to end of bock or at least come after TODO

### ISSUE THREAD

**Issue by WesHoward** [YU000jp/logseq-plugin-panel-coloring#3]
Tagging a couple TODO items with this the tag added by the context menu prepends on the line breaking the TODO formatting. I would like to have this appear after TODO.

Option 1 - Always after TODO and the priority tags.

Option 2 - Always after a predefined list of tags or text - which could include TODO and priority tags

Option 3 - Selector in the pop up to prepend or append and a setting to define default behavior.

**Comment by WesHoward** [comment]
And I want to add that this plugin has become an itegral part of my workflow since the author of admonition panels pulled his plugin. This has been so much more flexible and a fantastic experience and I would not switch back.

**Comment by WesHoward** [comment]
Updating this to add that its breaking H1/H2 etc formatting. The tag gets placed before the ## hashtags to mark the H level and I have to go back and manually correct it. So adding heading level formatting as something else to check for when adding tags through the popup.

**Comment by YU000jp** [comment]
fix at new release

Add to the end of the block instead of the beginning


Late reply. Sorry.
