### ISSUE TITLE
Is there an option to not render the tag?

### ISSUE THREAD

**Issue by HeatDeathOfUniverse** [YU000jp/logseq-plugin-panel-coloring#30]
Hello, I'm here again.
Nice to have such a plugin for beautifying logseq
In the process I set a tag color and when I use this tag it works fine, but when I create this new page it still works. The result is as follows
![image](https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/53603499/c01ba427-e630-4d5b-8bc0-3a36c577a128)
It should not work for [[page]], but only for #tag, right? I'm not sure if this is a bug or not. But I'd like to have a way or an option to prevent it from taking effect.

**Comment by YU000jp** [comment]
This is indeed an issue and I intend to fix it as a bug.

**Comment by YU000jp** [comment]
I released a new version. Please update.

**Comment by HeatDeathOfUniverse** [comment]
Thank you. I think it's been fixed.

**Comment by HeatDeathOfUniverse** [comment]
Sorry, but I just found out that Admonition has the same bug.
![image](https://github.com/YU000jp/logseq-plugin-panel-coloring/assets/53603499/70a9a141-ab57-43cd-9319-c5d9125de8bb)

**Comment by YU000jp** [comment]
I released a new version again. Please check it.

**Comment by HeatDeathOfUniverse** [comment]
Yes, It's worked! THX!
