### ISSUE TITLE
Built in tags are formatted based on a contains match leading to unexpected formatting

### ISSUE THREAD

**Issue by WesHoward** [YU000jp/logseq-plugin-panel-coloring#4]
I have a tag I use that is called ProcessInfo that is formatting like the built in INFO tag. Experimenting with this it seems that built in tags are partial matched resulting in unexpected formatting.

![Screenshot 2023-05-05 at 8 49 06 AM](https://user-images.githubusercontent.com/55550428/236476072-a518da5a-9132-4a06-a196-6afdc7f5ed9a.png)

Possible solutions:
1 - Regex match space hashtag word space|newline
 ``/\s#info(\s|\n)/gmi``

https://regex101.com/r/sKRW8F/1

2 - Make search case sensitive so my Info does not match the partial string INFO

**Comment by YU000jp** [comment]
Thank you very much. Indeed, that bug does exist. We will make a fix to ensure it doesn't match with any other tags
