### ISSUE TITLE
Tag formatting and precedence for the block is unclear

### ISSUE THREAD

**Issue by WesHoward** [YU000jp/logseq-plugin-panel-coloring#5]
See the below screenshot. The INFO tag seems to always win when used with other tags like SUCCESS and FAILED. While the tag text and background to format as expected, the overall panel is formatted based on the INFO tag.

![Screenshot 2023-05-05 at 8 56 54 AM](https://user-images.githubusercontent.com/55550428/236478127-88ff42d8-c8fe-4f19-9b2e-7f8421a905b3.png)

Possible solutions:
1 - Let me set the rank order these will be applied in in the settings. Something tagged with an urgency tag should be the main formatting consideration over something just informational

2 - Apply the tags in the order they appear in the block. Either the first or last tag is used as the primary block formatting for background and border.

**Comment by YU000jp** [comment]
To rank priority in the settings screen, a complex flow is required, which may be difficult to achieve. Therefore, I would like to finalize the simple priority here as it is challenging to implement.
I have a plan to rank the top positions on this list as the top-ranking. Until now, it has been the other way around.
          🔴#FAILED / #REMEDY, 
          🟠#WARNING / #LEARNED, 
          🟡#CAUTION / #DECLARATION, 
          🟢#SUCCESS / #FACTS, 
          🔵#NOTICE / #INFO / #REVIEW, 
          🟣#QUESTION / #DISCOVERY, 
          🟤#REPORT / #NOTE
